### PR TITLE
Development

### PR DESCRIPTION
**Pull request by zarath**
nearly 0.3.5

### CODE REVIEW

**Comment by zarath** [comment]
Are you sure, you have set the -H4 to 201 points in device settings window?

Screenshot_20200707_094914


2020-07-07 09:45:42,081 - NanoVNASaver.Hardware.NanoVNA_V2 - INFO - NanoVNAV2: set sweep start 200000000 step 1000000
2020-07-07 09:45:42,091 - NanoVNASaver.SweepWorker - DEBUG - Sending "finished" signal
2020-07-07 09:45:44,915 - NanoVNASaver.Windows.DeviceSettings - DEBUG - DP: 101
2020-07-07 09:45:48,752 - NanoVNASaver.Windows.DeviceSettings - DEBUG - DP: 203
2020-07-07 09:46:00,759 - NanoVNASaver.NanoVNASaver - DEBUG - Starting worker thread
2020-07-07 09:46:00,759 - NanoVNASaver.SweepWorker - INFO - Initializing SweepWorker

**Comment by RandMental** [comment]
Hi Holger

 

I start the H4 with 201 Points – no connection to the PC.

 



 

Next step is to run the Development branch in Pycharm – NanoVNA-saver screen appears

 

Click connect – almost immediately the NanoVNA changes to 101p, now I can do a screen dump:

 



 

The Device settings dialogue only has one dropdown option being  101

 



 

 

Debug.txt

2020-07-07 10:51:45,726 - NanoVNASaver - INFO - Startup...

2020-07-07 10:51:45,778 - NanoVNASaver.SweepWorker - INFO - Initializing SweepWorker

2020-07-07 10:51:45,779 - NanoVNASaver.NanoVNASaver - DEBUG - Building user interface

2020-07-07 10:51:47,061 - NanoVNASaver.Windows.About - INFO - Latest version is 0.3.4"

2020-07-07 10:51:47,061 - NanoVNASaver.Windows.About - INFO - This is 0.3.5-pre

2020-07-07 10:51:47,334 - NanoVNASaver.NanoVNASaver - DEBUG - New font width: 164.000000, normal font: 164.000000, factor: 1.000000

2020-07-07 10:51:47,822 - NanoVNASaver.Hardware.Hardware - DEBUG - Found NanoVNA USB:(0483:5740) on port COM25

2020-07-07 10:51:47,825 - NanoVNASaver.NanoVNASaver - DEBUG - Finished building interface

2020-07-07 10:51:56,427 - NanoVNASaver.NanoVNASaver - INFO - Connection COM25 (NanoVNA)

2020-07-07 10:51:56,531 - NanoVNASaver.Hardware.Hardware - INFO - Finding correct VNA type...

2020-07-07 10:51:56,632 - NanoVNASaver.Hardware.Hardware - INFO - Finding firmware variant...

2020-07-07 10:51:56,951 - NanoVNASaver.Hardware.Hardware - INFO - Type: NanoVNA-H4

2020-07-07 10:51:56,951 - NanoVNASaver.Hardware.VNA - DEBUG - Reading version info.

2020-07-07 10:51:57,153 - NanoVNASaver.Hardware.VNA - DEBUG - Found version info: 0.4.5-23-g587ad32ab

2020-07-07 10:51:57,153 - NanoVNASaver.Hardware.NanoVNA - DEBUG - Newer than 0.2.0, using new scan command.

2020-07-07 10:51:57,267 - NanoVNASaver.Hardware.VNA - DEBUG - Help command output:

2020-07-07 10:51:57,267 - NanoVNASaver.Hardware.VNA - DEBUG - help

 

Commands: version reset freq offset bandwidth time dac saveconfig clearconfig data frequencies port stat gain power sample scan sweep test touchcal touchtest pause resume cal save recall trace marker edelay capture vbat vbat_offset transform threshold help info color i2c lcd

 

ch> 

2020-07-07 10:51:57,386 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading frequencies

2020-07-07 10:51:57,573 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading frequencies (201 values)

2020-07-07 10:51:57,573 - NanoVNASaver.NanoVNASaver - INFO - Read starting frequency 850000000 and end frequency 925000000

2020-07-07 10:51:57,573 - NanoVNASaver.NanoVNASaver - DEBUG - Starting initial sweep

2020-07-07 10:51:57,574 - NanoVNASaver.NanoVNASaver - DEBUG - Starting worker thread

2020-07-07 10:51:57,574 - NanoVNASaver.SweepWorker - INFO - Initializing SweepWorker

2020-07-07 10:51:57,574 - NanoVNASaver.SweepWorker - INFO - 2 sweeps

2020-07-07 10:51:57,574 - NanoVNASaver.SweepWorker - DEBUG - Parsed sweep range as 850000000 to 925000000

2020-07-07 10:51:57,575 - NanoVNASaver.SweepWorker - DEBUG - Sweep segment no 0

2020-07-07 10:51:57,575 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 850000000 to 887313400

2020-07-07 10:51:57,576 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading frequencies

2020-07-07 10:51:58,143 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading frequencies (101 values)

2020-07-07 10:51:58,143 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0

2020-07-07 10:51:58,143 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading data 0

2020-07-07 10:51:58,346 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading data 0 (101 values)

2020-07-07 10:51:58,346 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values

2020-07-07 10:51:58,346 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1

2020-07-07 10:51:58,346 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading data 1

2020-07-07 10:51:58,548 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading data 1 (101 values)

2020-07-07 10:51:58,548 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values

2020-07-07 10:51:58,548 - NanoVNASaver.SweepWorker - DEBUG - Freqs: 101, values11: 101, values21: 101

2020-07-07 10:51:58,548 - NanoVNASaver.SweepWorker - DEBUG - Calculating data including corrections

2020-07-07 10:51:58,548 - NanoVNASaver.SweepWorker - DEBUG - Saving data to application (101 and 101 points)

2020-07-07 10:51:58,548 - NanoVNASaver.SweepWorker - DEBUG - Sending "updated" signal

2020-07-07 10:51:58,548 - NanoVNASaver.SweepWorker - DEBUG - Sweep segment no 1

2020-07-07 10:51:58,556 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 887686534 to 924999934

2020-07-07 10:51:58,566 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading frequencies

2020-07-07 10:51:59,128 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading frequencies (101 values)

2020-07-07 10:51:59,128 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0

2020-07-07 10:51:59,128 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading data 0

2020-07-07 10:51:59,330 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading data 0 (101 values)

2020-07-07 10:51:59,330 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values

2020-07-07 10:51:59,330 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1

2020-07-07 10:51:59,330 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading data 1

2020-07-07 10:51:59,531 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading data 1 (101 values)

2020-07-07 10:51:59,531 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values

2020-07-07 10:51:59,531 - NanoVNASaver.SweepWorker - DEBUG - Freqs: 202, values11: 202, values21: 202

2020-07-07 10:51:59,531 - NanoVNASaver.SweepWorker - DEBUG - Calculating data including corrections

2020-07-07 10:51:59,531 - NanoVNASaver.SweepWorker - DEBUG - Saving data to application (202 and 202 points)

2020-07-07 10:51:59,531 - NanoVNASaver.SweepWorker - DEBUG - Sending "updated" signal

2020-07-07 10:51:59,531 - NanoVNASaver.SweepWorker - DEBUG - Resetting NanoVNA sweep to full range: 850000000 to 925000000

2020-07-07 10:51:59,558 - NanoVNASaver.SweepWorker - DEBUG - Sending "finished" signal

2020-07-07 10:52:11,741 - NanoVNASaver.Hardware.VNA - DEBUG - Reading calibration info.

2020-07-07 10:52:13,410 - NanoVNASaver.Hardware.NanoVNA - DEBUG - Capturing screenshot...

2020-07-07 10:52:14,278 - NanoVNASaver.Hardware.NanoVNA - DEBUG - Captured screenshot

**Comment by zarath** [comment]
Can you try my current change?

**Comment by RandMental** [comment]
Sorry Holger was in a teleconference.

 

Unfortunately, still the same Debug.txt from you latest version:

The 201 point on the device gets reset back to 101p when Saver starts

 

 



 

2020-07-07 15:16:22,390 - NanoVNASaver - INFO - Startup...

2020-07-07 15:16:22,454 - NanoVNASaver.SweepWorker - INFO - Initializing SweepWorker

2020-07-07 15:16:22,455 - NanoVNASaver.Hardware.VNA - ERROR - Exception while reading help: Attempting to use a port that is not open

Traceback (most recent call last):

  File "C:\Workspaces\nanovna-saver-Zara\NanoVNASaver\Hardware\VNA.py", line 121, in readFromCommand

    drain_serial(self.serial)

  File "C:\Workspaces\nanovna-saver-Zara\NanoVNASaver\Hardware\Serial.py", line 29, in drain_serial

    cnt = len(serial_port.read(128))

  File "C:\Python\Python38\lib\site-packages\serial\serialwin32.py", line 267, in read

    raise portNotOpenError

serial.serialutil.SerialException: Attempting to use a port that is not open

2020-07-07 15:16:22,456 - NanoVNASaver.Hardware.VNA - DEBUG - Help command output:

2020-07-07 15:16:22,456 - NanoVNASaver.Hardware.VNA - DEBUG - 

2020-07-07 15:16:22,457 - NanoVNASaver.NanoVNASaver - DEBUG - Building user interface

2020-07-07 15:16:22,939 - NanoVNASaver.Windows.About - INFO - Latest version is 0.3.4"

2020-07-07 15:16:22,939 - NanoVNASaver.Windows.About - INFO - This is 0.3.5-pre

2020-07-07 15:16:23,143 - NanoVNASaver.NanoVNASaver - DEBUG - New font width: 164.000000, normal font: 164.000000, factor: 1.000000

2020-07-07 15:16:23,605 - NanoVNASaver.Hardware.Hardware - DEBUG - Found NanoVNA USB:(0483:5740) on port COM25

2020-07-07 15:16:23,608 - NanoVNASaver.NanoVNASaver - DEBUG - Finished building interface

2020-07-07 15:16:30,933 - NanoVNASaver.NanoVNASaver - INFO - Connection COM25 (NanoVNA)

2020-07-07 15:16:31,037 - NanoVNASaver.Hardware.Hardware - INFO - Finding correct VNA type...

2020-07-07 15:16:31,138 - NanoVNASaver.Hardware.Hardware - INFO - Finding firmware variant...

2020-07-07 15:16:31,253 - NanoVNASaver.Hardware.VNA - DEBUG - Help command output:

2020-07-07 15:16:31,253 - NanoVNASaver.Hardware.VNA - DEBUG - help

 

Commands: version reset freq offset bandwidth time dac saveconfig clearconfig data frequencies port stat gain power sample scan sweep test touchcal touchtest pause resume cal save recall trace marker edelay capture vbat vbat_offset transform threshold help info color i2c lcd

 

ch> 

2020-07-07 15:16:31,574 - NanoVNASaver.Hardware.Hardware - INFO - Type: NanoVNA-H4

2020-07-07 15:16:31,574 - NanoVNASaver.Hardware.NanoVNA_H - DEBUG - read_features

2020-07-07 15:16:31,807 - NanoVNASaver.Hardware.VNA - DEBUG - Help command output:

2020-07-07 15:16:31,807 - NanoVNASaver.Hardware.VNA - DEBUG - help

 

Commands: version reset freq offset bandwidth time dac saveconfig clearconfig data frequencies port stat gain power sample scan sweep test touchcal touchtest pause resume cal save recall trace marker edelay capture vbat vbat_offset transform threshold help info color i2c lcd

 

ch> 

2020-07-07 15:16:31,807 - NanoVNASaver.Hardware.VNA - DEBUG - Reading version info.

2020-07-07 15:16:32,009 - NanoVNASaver.Hardware.VNA - DEBUG - Found version info: 0.4.5-23-g587ad32ab

2020-07-07 15:16:32,009 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading frequencies

2020-07-07 15:16:32,179 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading frequencies (101 values)

2020-07-07 15:16:32,179 - NanoVNASaver.NanoVNASaver - INFO - Read starting frequency 850000000 and end frequency 925000000

2020-07-07 15:16:32,179 - NanoVNASaver.NanoVNASaver - DEBUG - Starting initial sweep

2020-07-07 15:16:32,179 - NanoVNASaver.NanoVNASaver - DEBUG - Starting worker thread

2020-07-07 15:16:32,180 - NanoVNASaver.SweepWorker - INFO - Initializing SweepWorker

2020-07-07 15:16:32,180 - NanoVNASaver.SweepWorker - INFO - 1 sweeps

2020-07-07 15:16:32,180 - NanoVNASaver.SweepWorker - DEBUG - Parsed sweep range as 850000000 to 925000000

2020-07-07 15:16:32,180 - NanoVNASaver.SweepWorker - DEBUG - Sweep segment no 0

2020-07-07 15:16:32,180 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 850000000 to 925000000

2020-07-07 15:16:32,181 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading frequencies

2020-07-07 15:16:32,401 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading frequencies (101 values)

2020-07-07 15:16:32,401 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0

2020-07-07 15:16:32,401 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading data 0

2020-07-07 15:16:33,002 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading data 0 (101 values)

2020-07-07 15:16:33,002 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values

2020-07-07 15:16:33,002 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1

2020-07-07 15:16:33,002 - NanoVNASaver.Hardware.VNA - DEBUG - VNA reading data 1

2020-07-07 15:16:33,304 - NanoVNASaver.Hardware.VNA - DEBUG - VNA done reading data 1 (101 values)

2020-07-07 15:16:33,304 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values

2020-07-07 15:16:33,304 - NanoVNASaver.SweepWorker - DEBUG - Freqs: 101, values11: 101, values21: 101

2020-07-07 15:16:33,304 - NanoVNASaver.SweepWorker - DEBUG - Calculating data including corrections

2020-07-07 15:16:33,304 - NanoVNASaver.SweepWorker - DEBUG - Saving data to application (101 and 101 points)

2020-07-07 15:16:33,305 - NanoVNASaver.SweepWorker - DEBUG - Sending "updated" signal

2020-07-07 15:16:33,305 - NanoVNASaver.SweepWorker - DEBUG - Sending "finished" signal

2020-07-07 15:16:35,232 - NanoVNASaver.Hardware.VNA - DEBUG - Reading calibration info.

**Comment by zarath** [comment]
I've changed some debugging output @RandMental can you gif it another try.
Would prefer -D debugfile.txt as attachment here

**Comment by zarath** [comment]
> Hi, using nanovna-H4 with DiSlord 0.8.4.7 its being detected as nanoVNA only, and not possible to configure 201 points at nanovna-saver.

can you supply me debug.txt

nanovna-saver.py -D debug.txt

file can be attached by drag and drop here

**Pull request merged**
