### PR TITLE
Development

### PR DESCRIPTION
**Pull request by zarath**

### CODE REVIEW

**Comment by RandMental** [comment]
Hi HolgerFirst thanks for the development you have done. I unfortunately had to go back to v0.2.2 build with DiSlord version of hardware.py, for use with a - H4. Pc is Win 10 64bitI tried V0.3.2, but it still crashes, does not recognise the -H4 and its 201 sweep points.  Even setting the H4 to 101 points, it still crashes with an index fault. Happy to help with further debugging this coming week. Regards
-------- Original message --------From: Holger Müller <notifications@github.com> Date: 2020/06/28  19:02  (GMT+02:00) To: zarath/nanovna-saver <nanovna-saver@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [zarath/nanovna-saver] Development (#28) 
Merged #28 into master.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zarath/nanovna-saver/pull/28#event-3490500594",
"url": "https://github.com/zarath/nanovna-saver/pull/28#event-3490500594",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zarath** [comment]
Where to find this hardware.py frm DiSlord?

**Comment by RandMental** [comment]
Hi Holger

 

Attached it the full V0.2.2 project with the Hardware.py replaced, as I currently use with the H4, it is stable. 

I have hoped to move step t it to V0.2.2.1 with the last commits from Rune in Feb and then the H4 update from DiSlord.

 

However,  if you can merge it with your V0.3.x that would be much better.

 

Regards

Rand

**Comment by RandMental** [comment]
[nanovna-saver-0.2.2.zip](https://github.com/zarath/nanovna-saver/files/4842785/nanovna-saver-0.2.2.zip)

[Hardware.py.zip](https://github.com/zarath/nanovna-saver/files/4842787/Hardware.py.zip)

**Pull request merged**
